config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :searches, only: [:index, :new, :create, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :searches
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :search

  monetize :price_cents
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :offers, dependent: :destroy

  validates :query, :zip_code, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :searches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  protected

  def after_sign_in_path_for(resource)
    searches_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    redirect_to searches_path if current_user
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_categories, only: [:index, :new, :create]

  def index
    @category = Category.find(params[:category_id]) unless params[:category_id].nil? || params[:category_id].empty?
    if @category
      @searches = current_user.searches.where(category: @category).order(created_at: :desc)
    else
      @searches = current_user.searches.order(created_at: :desc)
    end
  end

  def show
    @search = current_user.searches.find(params[:id])
  end

  def new
    @search     = Search.new
  end

  def create
    @search      = Search.new(search_params)
    @search.user = current_user

    if @search.save
      redirect_to searches_path
    else
      render :new
    end
  end

  def destroy
    @search = current_user.searches.find(params[:id])
    @search.destroy
    redirect_to searches_path
  end

  private

  def search_params
    params.require(:search).permit(:query, :zip_code, :category_id)
  end

  def set_categories
    @categories = Category.all.order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title = t('brand')
    / = favicon_link_tag ''
    = csrf_meta_tags
    = stylesheet_link_tag "https://use.fontawesome.com/releases/v5.4.1/css/all.css", integrity: "sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz", crossorigin: "anonymous"
    / = stylesheet_pack_tag 'application', media: 'all'
    = stylesheet_link_tag 'application', media: 'all'
  body
    = render 'shared/navbar'
    = yield
    = javascript_include_tag 'application'
    = javascript_pack_tag 'application'

app/views/offers/_card.html.slim
.flat-card
  .flat-card-body
    .flexbox.flexbox-between.flexbox-align-top
      h3.flat-title = offer.title
      .price-tag = "#{humanized_money(offer.price)}€"
    p = offer.description
  .flat-card-footer.flexbox.flexbox-center
    .flexitem-main
      | Il y a
      =< distance_of_time_in_words_to_now(offer.lbc_date)
    .flexitem
      .flat-button-group
        = link_to t('.show'), offer.url, target: '_blank', rel: 'noopener noreferrer', class: 'flat-button'

app/views/pages/home.html.slim
.container
  .level
    .flexbox.flexbox-align-top
      = image_tag "logo"
      .flat-brand = t('brand_html')

  .columns
    .column.is-4-desktop.is-offset-4-desktop.is-6-tablet.is-offset-3-tablet
      .flat-card
        .flat-card-body
          .flexbox.flexbox-between.flexbox-align-top
            h3.flat-title = t('.brand_message')

          p = t('.app_description')
        .flat-card-footer.flexbox.flexbox-center
          .flexitem-main
          .flexitem
            .flat-button-group
              = link_to t('sign_up'), new_user_registration_path, class: 'flat-button flat-button-primary'

app/views/searches/_card.html.slim
= link_to search_path(search) do
  .flat-card.flat-card-link
    .flat-card-body
      .flexbox.flexbox-between.flexbox-align-top
        h3.flat-title = search.query
        p
          i class=("fas fa-#{search.category.icon_name}") title=(search.category.title)
      p = t('offers', count: search.offers.count)
    .flat-card-footer
      .flexitem-main
      .flexitem
        .flat-button-group
          = link_to t('.delete'), search_path(search), method: :delete, class: 'flat-button flat-button-small'

app/views/searches/index.html.slim
.container
  .flexbox.flexbox-between.flexbox-align-top.flexbox-wrap
    h1.flat-title
      = t('searches', count: @searches.count)
    = link_to t('.new_search'), new_search_path, class: 'flat-button flat-button-primary'


  .level
    .flat-button-group
      p.is-uppercase = t('.filter_by')
      - if @category
        = link_to t('.all_categories'), searches_path(category_id: ""), class: 'flat-button'
      - @categories.each do |category|
        = link_to searches_path(category_id: category.id), class: "flat-button #{'flat-button-active' if category == @category}" do
          i class=("fas fa-#{category.icon_name}")
          =< category.title

  .columns
    - @searches.each do |search|
      .column.is-4-desktop.is-6-tablet
        = render 'card', search: search

app/views/searches/new.html.slim
.hero.is-medium
  .hero-body
    .container
      .columns
        .column.is-4-desktop.is-offset-4-desktop.is-6-tablet.is-offset-3-tablet
          = simple_form_for @search, html: { class: 'flat-form' } do |f|
            h2.flat-title.has-text-centered = t('.new_search')
            = f.association :category, collection: @categories
            = f.input :query
            = f.input :zip_code

            .flat-form-footer.flexbox.flexbox-center
              .flexitem-main
              .flexitem
                .flat-button-group
                  = link_to t('cancel'), searches_path, class: 'flat-button'
                  = f.submit t('.search'), class: 'flat-button flat-button-primary'

app/views/searches/show.html.slim
.container
  .flexbox.flexbox-between.flexbox-align-top.flexbox-wrap
    h1.flat-title
      i class=("fas fa-#{@search.category.icon_name}") title=(@search.category.title)
      =<> @search.query
      | (
      =<> t('offers', count: @search.offers.count)
      | )
    = link_to t('.all_searches'), searches_path, class: 'flat-button'
  .columns
    - @search.offers.each do |offer|
      .column.is-4-desktop.is-6-tablet
        = render 'offers/card', offer: offer

app/views/shared/_navbar.html.slim
.flat-navbar
  .flexbox.flexbox-between.flexbox-wrap
    .flexitem-main
      - unless params[:action] == 'home'
        .flexbox.flexbox-align-top
          = image_tag "logo-reverse"
          .flat-brand-reverse = t('brand_html')
    .flexitem
      .flat-button-group
        - if current_user
          = link_to t('sign_out'), destroy_user_session_path, method: :delete, class: 'flat-button flat-button-small'
        - else
          - if controller_name != 'sessions'
            = link_to t('sign_in'), new_user_session_path, class: 'flat-button'
          - else
            = link_to t('forgot_password'), new_password_path(resource_name), class: 'flat-button '
            = link_to t('sign_up'), new_registration_path(resource_name), class: 'flat-button flat-button-primary'